name: whenworks
id: https://w3id.org/whenworks
description: Data models for the WhenWorks API
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string

classes:
  Event:
    slots:
      - name
      - desc
      - dates
      - users
  User:
    slots:
      - name
      - comment
      - dates
  DateRange:
    slots:
      - from
      - to
      - preferred

slots:
  name:
    description: The name of the event
    required: true
  desc:
    description: A description of the event
  dates:
    description: The dates of the event
    range: DateRange
    multivalued: true
    inlined_as_list: true
  users:
    description: The users of the event
    range: User
    multivalued: true
    inlined: true
    inlined_as_list: false
  name:
    description: The name of the user
    required: true
    identifier: true
  comment:
    description: A comment from the user
  dates:
    description: The availability dates of the user
    range: DateRange
    multivalued: true
    inlined_as_list: true
  from:
    description: The start date of the availability
    required: true
    range: integer
  to:
    description: The end date of the availability
    required: true
    range: integer
  preferred:
    description: Whether the user prefers this date
    required: true
    range: boolean
    ifabsent: False
