[package]
name = "schedule_thing"
version = "0.1.0"
edition = "2021"

[dependencies]
# rusqlite = { version = "0.29.0", features = ["bundled"] }
# hashbrown = "0.14.0"
rand = "0.8.5"
bincode = "1.3.3"
serde = { version = "^1.0", features = ["derive", "rc"] }
serde_json = "1.0.105"
# flate2 = { version = "1.0.27", features = ["zlib"], default-features = false }

[profile.release]
lto = true
opt-level = 3 
codegen-units = 1
debug = false
strip = "all"

